### ISSUE TITLE
Velocity errors

### ISSUE THREAD

**Issue by NoltoxGit** [retrooper/packetevents#924] opened 2024-08-11 11:31 UTC
**Describe the bug**
I've a lot of errors with Velocity.
I use the latest PacketEvents build (2.5.0+e04cd2108-SNAPSHOT)

**Software brand**
Velocity 3.3.0-SNAPSHOT (git-7c9a9761)

**Plugins**
Plugins: ajqueue, azlink, commandforward, leaf, litebans, luckperms, maintenance, maintenanceaddon, miniplaceholders, packetevents, pl-hide-pro, plan, premiumvanish, protocolize, signedvelocity, sonar, spark

**Expected behavior**
No errors

**Additional context**
Logs: https://mclo.gs/XX5jmiB

**Comment by rafi67000** [comment] 2024-08-11 19:26
protocolize was known to be incompatible with pe but that's not related to that issue.
I have the same issue.

**Comment by rafi67000** [comment] 2024-08-11 19:28
duplicate of #922

**Comment by booky10** [comment] 2024-08-12 04:24
fixed with #927

**Closed as completed** 2024-08-12 04:24 UTC
Labels: bug
