### ISSUE TITLE
Client DecoderException when PacketLoginSendEvent listener is processed for too long

### ISSUE THREAD

**Issue by Souvlakis** [retrooper/packetevents#522] opened 2023-01-13 20:09 UTC
**Describe the bug**
A DecoderException is thrown on a Minecraft client instance when a PacketEvents-dependant plugin takes too long (200ms is enough) to process ``PacketLoginSendEvent`` on **LOGIN_SUCCESS** packet.

~~The error happens only **once** per unique player per server uptime. The first connection is disconnected, every consecutive connection goes through fine.~~

~~This **does not** apply when the client version corresponds with the server version.~~

I was able to successfully reproduce with 1.18.2 lunar client, 1.8.8 server, ViaVersion 4.5.0.
The plugin I reproduced the issue with can be found at https://github.com/Souvlakis/PacketEvents-Bug

**Software brand**
Imanity Spigot 2022.05.2 LTS BUILD 4 (1.8.8)
Should affect any 1.8.8 spigot build/fork

**Plugins**
ViaVersion v4.5.0
ProtocolLib v5.0.0-SNAPSHOT-b600
PacketEvents-Bug (the plugin I reproduced the issue with)

**How To Reproduce**
1. Join with the 1.18.2 vanilla minecraft client.
2. Expect a DecoderException kick
~~3. Join again~~
~~4. Observe no further kicks until server restarts~~

**Expected behavior**
A DecoderException kick should not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/64416763/212410084-b05c2292-e496-4abe-a765-0eab5890f23a.png)

**Comment by MWHunter** [comment] 2023-01-27 19:42
unable to reproduce on a 1.19.3 server

**Comment by MWHunter** [comment] 2023-01-27 21:26
able to reproduce on a 1.8 server.  However, disabling everything including the internal packet listener still causes the exception to be thrown.  This leads me to believe that this is a vanilla bug rather than a packetevents one.

**Comment by MWHunter** [comment] 2023-08-20 16:37
closing due to being a vanilla bug

**Closed by MWHunter** 2023-08-20 16:37 UTC
Labels: bug
