### ISSUE TITLE
WrapperPlayClientClickWindow bug with quick-move

### ISSUE THREAD

**Issue by Betterovsky** [retrooper/packetevents#578] opened 2023-04-27 17:21 UTC
**Describe the bug**
The ItemStack is always null using WrapperPlayClientClickWindow quick-move with the $getCarriedItemStack() method.

**Software brand**
git-Purpur-1171 (MC: 1.16.5)

**Plugins**
Only my testing plugin.

**How To Reproduce**
Steps to reproduce the behavior: (PacketEvents 2.0)

Check if the receiving packet is the PacketType.Client.CLICK_WINDOW packet
Check if the WindowClickType is WindowClickType.QUICK_MOVE
Use quick-move with some random items on e.g. a furnace
Check the output from the ItemStack

**Expected behavior**
The ItemStack which I quick-moved

**Screenshots**
Not needed ig as it's just null
ItemStack[null]

**Additional context**
A similar theme:
https://github.com/retrooper/packetevents/issues/344

**Comment by MWHunter** [comment] 2023-04-27 18:14
Click an item so it's on your cursor.  Then quickmove an item.  Is carried item stack null then?

**Comment by MWHunter** [comment] 2023-04-27 22:02
I'm saying because this is the item you have picked up with your cursor.  It is not the item that you are moving.  If you left click an item without setting it down, then shift click another item it shouldn't be null.

**Comment by MWHunter** [comment] 2023-05-08 19:20
closing because this wrapper is working as intended, not a packetevents issue

**Closed by MWHunter** 2023-05-08 19:20 UTC
Labels: bug
