### ISSUE TITLE
Enchants are acting strangely

### ISSUE THREAD

**Issue by SamB440** [retrooper/packetevents#942] opened 2024-08-15 19:15 UTC
**Describe the bug**
With a 1.21 server, ViaVersion + ViaBackwards + Grim, first join with a client older than 1.21. Use a trident with riptide - it will false, packetevents seems to not be reading enchants. Join with a 1.21 client and it will false as well. But then restart the server, and join with a 1.21 client first. Enchants can be read correctly. Joining with a 1.20.6 client does not false. 

**Software brand**
Paper 1.21

**Plugins**
Grim, ViaVersion, ViaBackwards

**How To Reproduce**
See above.

**Expected behavior**
Enchants should be readable no matter what version joins first

**Screenshots**

**Additional context**

**Comment by booky10** [comment] 2024-08-17 14:31
I can't reproduce this, packetevents does read enchantments correctly if I dump the contents of SET_SLOT packets
Tested both 1.20.6 client and then 1.21.1 and the other way around (with a restart of course)

Using latest Paper (1.21.1 build 26)
Using latest ViaVersion (v5.0.4 build 927)
Using latest ViaBackwards (v5.0.4 build 480)
Using latest packetevents (a3e65cfcbe0f195f735eaf91868b2988d1f3a660)

Is there any repro step missing? Could it be a Grim issue?

**Comment by SamB440** [comment] 2024-08-17 14:52
The code that falses (for this test example) is https://github.com/GrimAnticheat/Grim/blob/39605b72d2d68bc7393f022e9be3cbd315fcea49/src/main/java/ac/grim/grimac/events/packets/PacketPlayerDigging.java#L107

I don't think it makes sense to be a Grim issue because it's entirely dependent on what client version joins first

**Comment by SamB440** [comment] 2024-08-17 14:54
I shall test again and see if I can notice anything

**Comment by SamB440** [comment] 2024-08-17 15:00
Yeah on a 1.20.6 client that joins first, `getEnchantmentLevel` returns 0, if a 1.21 client joins first then it returns the correct value of 1.

**Comment by booky10** [comment] 2024-08-17 17:13
Should be fixed by https://github.com/retrooper/packetevents/pull/950, could you verify using your setup?

**Comment by SamB440** [comment] 2024-08-17 17:23
I can confirm that fixes the problem

**Closed as completed** 2024-08-17 17:57 UTC
Labels: bug
