### ISSUE TITLE
1.17/1.12/1.8 + ProtocolLib + ViaVersion causes client to throw a DecoderException

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#245] opened 2022-02-16 05:34 UTC
Everything works fine without ProtocolLib, but there's something seriously wrong with injecting with protocollib.

**Comment by retrooper** [comment] 2022-02-16 19:29
https://github.com/retrooper/packetevents/issues/233

**Comment by retrooper** [comment] 2022-02-18 21:16
The issue is packetevents encoder is called before ProtocolLib, and ProtocolLib's encoder can only listen to NMS packets, so we are passing them bytes, which they likely discard or atleast ignore.

**Comment by retrooper** [comment] 2022-02-18 21:17
We need to somehow adjust our position in the pipeline, issue is our channel initialization is handled before them.

**Comment by retrooper** [comment] 2022-02-20 17:07
Yea that commit did basically nothing

**Comment by retrooper** [comment] 2022-02-21 20:34
Fixed in https://github.com/retrooper/packetevents/commit/03a5f8ec906a42987d7b505085f45ac10ba343de and https://github.com/retrooper/packetevents/commit/dd1c35dfb31250481d883560918eb08fc4af368f

**Closed by retrooper** 2022-02-21 20:34 UTC
Labels: bug
