### ISSUE TITLE
Shadow colors appears to break in older versions of MC

### ISSUE THREAD

**Issue by libraryaddict** [retrooper/packetevents#1077] opened 2024-12-03 23:59 UTC
**Describe the bug**

When using latest builds of PacketEvents & Lib's Disguises, users are denied entry to the server as shadow colors are attempted to be parsed but method not found.

This appears to be caused by https://github.com/retrooper/packetevents/commit/575aa4619c3bc143681bd0a1371e7f903491f28d

https://mclo.gs/IwsJvOk
Rehosted: https://pastebin.com/saMRTQud

**Software brand**

 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) for Minecraft 1.21.1

**Plugins**

LibsDisguises (10.0.44-SNAPSHOT), packetevents (2.7.0+70d94137d-SNAPSHOT)

**How To Reproduce**

1. Start 1.21.1 Paper Server with the two plugins installed
2. Try to join
3. Get error

**Expected behavior**

PacketEvents not to try use a missing method

**Additional context**

https://mclo.gs/IwsJvOk
Rehosted: https://pastebin.com/saMRTQud

**Comment by booky10** [comment] 2024-12-04 17:05
This was caused by packetevents shading the adventure library
It should now be fixed by d6c81f32cd7ba4a6f03e6e07712306dc14949007

**Closed as completed by booky10** 2024-12-04 17:05 UTC
Labels: bug
