### ISSUE TITLE
Packet Events Proxy Spam

### ISSUE THREAD

**Issue by YusakiDev** [retrooper/packetevents#1031] opened 2024-10-19 11:27 UTC
**Describe the bug**
I have no idea what this is but it happen on velocity and it's quite flodding console

**Software brand**
Please let us know what software you are using.
Eg. Spigot 1.18.2, Paper 1.18.2, Tuinity 1.18.2, Pufferfish 1.18.2, etc...
Make sure to mention the version of the software.

Velocity 3.3.0

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
Eg. ViaVersion, ProtocolLib, HolographicDisplays
You may also provide a screenshot.
![javaw_PBey7IJf74](https://github.com/user-attachments/assets/710822ae-7c86-4496-9bea-dbc4af9f551a)

**How To Reproduce**
*Example:*
1. Runs server normally 
2. Suspect when people enters limbo

**Expected behavior**
no errors.

**Screenshots**

**Additional context**
```
[18:25:34 INFO]: [server connection] GGEZsPORT -> limbo has connected
[18:25:34 WARN] [com.github.retrooper.packetevents.PacketEventsAPI]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IllegalArgumentException: Expected NBTByte but got NBTInt
        at com.github.retrooper.packetevents.util.adventure.AdventureNBTSerializer.requireType(AdventureNBTSerializer.java:759) ~[?:?]
        at com.github.retrooper.packetevents.util.adventure.AdventureNBTSerializer.access$200(AdventureNBTSerializer.java:75) ~[?:?]
        at com.github.retrooper.packetevents.util.adventure.AdventureNBTSerializer$NBTReader.lambda$useBoolean$0(AdventureNBTSerializer.java:566) ~[?:?]
        at com.github.retrooper.packetevents.util.adventure.AdventureNBTSerializer$NBTReader.useTag(AdventureNBTSerializer.java:676) ~[?:?]
        at com.github.retrooper.packetevents.util.adventure.AdventureNBTSerializer$NBTReader.useBoolean(AdventureNBTSerializer.java:566) ~[?:?]
        at com.github.retrooper.packetevents.util.adventure.AdventureNBTSerializer.deserializeStyle(AdventureNBTSerializer.java:333) ~[?:?]
        at com.github.retrooper.packetevents.protocol.chat.ChatTypeDecoration.decode(ChatTypeDecoration.java:93) ~[?:?]
        at com.github.retrooper.packetevents.protocol.chat.ChatType.decode(ChatType.java:97) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler$RegistryEntry.handleElement(SynchronizedRegistriesHandler.java:188) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler$RegistryEntry.createFromElements(SynchronizedRegistriesHandler.java:224) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler.lambda$handleRegistry$0(SynchronizedRegistriesHandler.java:113) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler$RegistryEntry.lambda$computeSyncedRegistry$0(SynchronizedRegistriesHandler.java:171) ~[?:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler$RegistryEntry.computeSyncedRegistry(SynchronizedRegistriesHandler.java:170) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler.handleRegistry(SynchronizedRegistriesHandler.java:112) ~[?:?]
        at com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler.handleLegacyRegistries(SynchronizedRegistriesHandler.java:131) ~[?:?]
        at com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:94) ~[?:?]
        at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
        at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:46) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:70) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:32) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueOutboundHandler.write(PlayPacketQueueOutboundHandler.java:67) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:234) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.handle(ConfigSessionHandler.java:271) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.protocol.packet.config.RegistrySyncPacket.handle(RegistrySyncPacket.java:48) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:153) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueInboundHandler.channelRead(PlayPacketQueueInboundHandler.java:62) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:91) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[proxy.jar:3.3.0-SNAPSHOT (git-ffa78d2a-b435)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        ```

**Comment by booky10** [comment] 2024-10-21 14:33
Duplicate of #1008, which has been fixed in #1009

If you don't want to wait until the next release, use the snapshot builds [from jenkins](https://ci.codemc.io/job/retrooper/job/packetevents/)

**Closed as not planned by booky10** 2024-10-21 14:33 UTC
Labels: bug
